### PR TITLE
Added gentx/gentx-in3s.com.json.

### PR DESCRIPTION
**Pull request by davepuchyr**

### CODE REVIEW

**Comment by davepuchyr** [comment]
How do I trigger certus-bot?

**Comment by leoluk** [comment]
It's still invalid, the bot will reply as soon as the state changes.

**Comment by davepuchyr** [comment]
> It's still invalid, the bot will reply as soon as the state changes.

Thanks, Leo.

**Comment by ebuchman** [comment]
Lol 100% commission ? Nice work

**Comment by davepuchyr** [comment]
> Lol 100% commission ? Nice work

Believe it!  This validator only exists to facilitate the decentralization of the network.  Only delegate to it for that reason and that reason alone.  ie, Throw it some scraps just to keep it in the top 100.

**Pull request merged**
