### PR TITLE
Cosmoshub-3 Genesis

### PR DESCRIPTION
**Pull request by jackzampolin**

### CODE REVIEW

**Comment by ValarDragon** [comment]
It'd be cool if we added a bot here that replies with the sha256sum of the genesis, to make checking easy.

**Comment by jackzampolin** [comment]
Jack bot activated:

```
~/.gaiad/config $ jq -S -c -M '' genesis.json | shasum -a 256
749c3244ed1bda96309d12b44184666423a258f8aeb249d94dec8b69c0fc83de  -
```

**Comment by alexanderbez** [comment]
@jackzampolin please update the README too.

**Comment by nylira** [comment]
The hash of this genesis file matches the hash computed by the nylira.net validator.

**Pull request merged**
