### PR TITLE
Push genesis file, gentx folder and a couple of README updates

### PR DESCRIPTION
**Pull request by jackzampolin**

### CODE REVIEW

**Comment by chris-remus** [comment]
This timing feels very arbitrary, rushed and risky. Also, have any of the audit results been published?

**Comment by zmanian** [comment]
Audit state

https://blog.cosmos.network/audits-audits-everywhere-everything-you-need-to-know-about-application-security-and-the-cosmos-76130f69aa60

**Comment by dlguddus** [comment]
I saw the double signing slashing amount reduced to 5%. It is related to the risk of unstable software and lack of firmly tested kms software. In line with this, isn't it also necessary to unable the tombstone feature for a while, until we have strong confidence about those stability? Slashing amount is critical but tombstone is a death sentence for validators.

**Comment by 7alisman** [comment]
Here is my issue:

Originally when the decision was made to go to mainnet without a production ready and audited KMS system, it was prior to the introduction of the account tombstone functionality. Now that accounts can be tombstoned however, it puts us as Validators into a position where we have to weigh the risk of a possible loss of 100% of our delegations for an accidental double sign while ironing our any possible kinks in the KMS, vs the considerably less secure option of just running the software.

I don't know about anyone else, but this is a scary situation in my opinion, and frankly I believe that (even with the reduced penalty for double sign) mainnet should have been blocked by either one of the following:

1) Audited/Production ready KMS
2) Addition of Key cycling capability
3) Removal of Tombstone (or even an increased jail period for double sign and a deferral of tombstoning the key till the second occurance.

I mean, I am comfortable with a non-production ready kms if I have the at least one opportunity to identify and fix a bug in the KMS that caused the double sign. I am also comfortable with first offence tombstoning if I can cycle to a different key without losing my delegation. However, it gives me butterflies in my stomach thinking about the damage it does to our business model if we lose all of our delegations due to a bug in the KMS we are using in an attempt to increase security.

As is, it feels like validator teams are forced to weigh the business risk of losing delegations against the security of a hsm.

**Comment by zmanian** [comment]
So the KMS audit completion is weeks away, we did merge alpha double signing/roll back protection over the weekend.

Iqlusion is going to run with this in production.
Key cycling capabilities has huge implications for light clients and IBC. Basically at best you'll only be able to rotate a key every three weeks. It's not going to be hugely helpful.

The big message is that you don't need to a genesis validator. Having an account in genesis lets you create a validator anytime after launch as well.

if you feel at all uncomfortable with the state of validator setups, I recommend waiting.

**Comment by jaekwon** [comment]
The tombstone system is there to protect the validator from getting slashed to 0 due to continuous repeated slashing/unjailing violations from an attacker, so we should keep it as is.  As a delegator, I prefer to opt-into delegating a validator after it's double-signed.  I'd only want to re-delegate after regaining confidence in its ability to prevent a future double-spend, which would require some explanation & a new consensus key.

Validators who don't audit KMS at this time should run the default software that uses the filesystem, and use sentry nodes to protect against unwanted intrusion or downtime.

**Comment by dlguddus** [comment]
Thank you for your reply zaki and jaekwon. After long consideration, B-Harvest decided not to join on genesis block and also after some period of time from genesis to protect our delegators from relatively high risk of slashing.
Also, I agree about what jaekwon said about tombstone.

**Pull request merged**
